### ISSUE TITLE
Dependencies update | ksp dependency handler migration

### ISSUE THREAD

**Issue by mariomanhique** [android/nowinandroid#1027]
Updated dependency handler from kapt to ksp in AndroidHiltConvetionPlugin 
Updated dependency handler from kapt to ksp in  sync:work and core:domain modules

Updated dependencies:
hiltExt = "1.0.0" to hiltExt = “1.1.0”

firebaseBom = "32.4.0" to firebaseBom = "32.5.0”

 androidxNavigation = "2.7.4" to androidxNavigation = “2.7.5”

androidxHiltNavigationCompose = “1.0.0” to  androidxHiltNavigationCompose = “1.1.0”

androidxComposeRuntimeTracing = "1.0.0-alpha03" to  androidxComposeRuntimeTracing = "1.0.0-alpha04”

androidDesugarJdkLibs = "2.0.3" to  androidDesugarJdkLibs = “2.0.4”

**Comment by mariomanhique** [comment]
I had to revert to  androidxComposeRuntimeTracing = "1.0.0-alpha03", I learned that androidxComposeRuntimeTracing = "1.0.0-alpha04” throws exceptions such as:

### 1. Error 1
Failed to get FIS auth token
                                                                                                    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException
                                                                                                    	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.2:5)
                                                                                                    	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
                                                                                                    	at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(GmsRpc.java:260)
                                                                                                    	at com.google.firebase.messaging.GmsRpc.startRpc(GmsRpc.java:222)
                                                                                                    	at com.google.firebase.messaging.GmsRpc.getToken(GmsRpc.java:180)
                                                                                                    	at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$10$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:611)
                                                                                                    	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda7.start(Unknown Source:6)
                                                                                                    	at com.google.firebase.messaging.RequestDeduplicator.getOrStartGetTokenRequest(RequestDeduplicator.java:67)
                                                                                                    	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:607)
                                                                                                    	at com.google.firebase.messaging.SyncTask.maybeRefreshToken(SyncTask.java:123)
                                                                                                    	at com.google.firebase.messaging.SyncTask.run(SyncTask.java:93)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: com.google.firebase.installations.FirebaseInstallationsException
                                                                                                    	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:414)
                                                                                                    	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$3$com-google-firebase-installations-FirebaseInstallations(FirebaseInstallations.java:372)
                                                                                                    	at com.google.firebase.installations.FirebaseInstallations$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at com.google.firebase.concurrent.SequentialExecutor$1.run(SequentialExecutor.java:117)
                                                                                                    	at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:229)
                                                                                                    	at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:174)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
                                                                                                    	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)

### 2. Error 2
Error failing to fetch the remote configs: Bad response code: 400
2023-11-10 09:06:48.013  4459-4504  FirebaseCrashlytics     com....apps.nowinandroid.demo.debug  E  Settings request failed.
                                                                                                    java.io.FileNotFoundException: https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/Your:App:Id/settings?instance=8dadf8600b595dafc0675a0aff64e281c95f355d&build_version=8&display_version=0.1.2&source=1
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
                                                                                                    	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:82)
                                                                                                    	at com.google.firebase.crashlytics.internal.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:112)
                                                                                                    	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
                                                                                                    	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
                                                                                                    	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)

### 3. Error 3
FATAL EXCEPTION: main
                                                                                                    Process: com.google.samples.apps.nowinandroid.demo.debug, PID: 4459
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
                                                                                                    	at androidx.compose.ui.platform.MotionDurationScaleImpl.<init>(WindowRecomposer.android.kt:440)
                                                                                                    	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:341)
                                                                                                    	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:325)
                                                                                                    	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168)
                                                                                                    	at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)
                                                                                                    	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:300)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.onAttachedToWindow(ComposeView.android.kt:283)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:21290)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2820)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:832)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.runtime.PrimitiveSnapshotStateKt" on path: DexPathList[[zip file "/data/app/~~KiWL-eunLAkn96rPxiE41g==/com.google.samples.apps.nowinandroid.demo.debug-_b8Uff2xa_D0vqc5m8ElYg==/base.apk"],nativeLibraryDirectories=[/data/app/~~KiWL-eunLAkn96rPxiE41g==/com.google.samples.apps.nowinandroid.demo.debug-_b8Uff2xa_D0vqc5m8ElYg==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
