### ISSUE TITLE
[Bug]: Nia will be crash if I package it to a demo release apk to install on phone, because I replace my own code or delete the code in setContent

### ISSUE THREAD

**Issue by lcpp6** [android/nowinandroid#1619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

【Bug】I conducted the following tests:
1) Directly package the original project as. apk and install it on the phone --->will not crash
2) Delete the following code and then perform operation 1->apk crashes!
 delete this code : MainActivity/onCreate/CompositionLocalProvider(
                LocalAnalyticsHelper provides analyticsHelper,
                LocalTimeZone provides currentTimeZone,
            ) {
                ...
            }

Why is that?
If I try to replace setContent{xxx} with my own Compose function，then package it as a demo release apk to install on my phone，it will be crash !

I has no this proplem on the version 0.1.2  of Nia.

### Relevant logcat output

```shell
java.lang.IllegalArgumentException: Multiple entries with same key: C4.d=true and C4.d=true
	at W2.f.a(SourceFile:85)
	at C0.d.b(SourceFile:24)
	at com.google.samples.apps.nowinandroid.MainActivity.j(SourceFile:64)
	at H0.e.getValue(SourceFile:23)
	at h4.i.o(SourceFile:31)
	at h4.i.h(SourceFile:13)
	at androidx.lifecycle.K.o(SourceFile:33)
	at androidx.lifecycle.K.h(SourceFile:13)
	at a6.k.x(SourceFile:5)
	at B5.U.d(SourceFile:10)
	at androidx.lifecycle.L.o(SourceFile:72)
	at k5.a.r(SourceFile:9)
	at H5.a.f(SourceFile:124)
	at B5.a.h0(SourceFile:99)
	at B5.U.h(SourceFile:36)
	at androidx.lifecycle.M.f(SourceFile:20)
	at androidx.lifecycle.w.a(SourceFile:23)
	at androidx.lifecycle.x.h(SourceFile:330)
	at androidx.lifecycle.x.e(SourceFile:77)
	at androidx.lifecycle.x.d(SourceFile:15)
	at androidx.lifecycle.e0.b(SourceFile:25)
	at androidx.lifecycle.Q.onActivityPostStarted(SourceFile:10)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1494)
	at android.app.Activity.performStart(Activity.java:8589)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3850)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Suppressed: H5.e: [r0{Cancelling}@e61fbd5, Dispatchers.Main.immediate]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lcpp-nt** [comment]
It seems to be the same issue as # 1569. I compared the mapping file and found that there are two ViewModel=true.But this is just my guess now!
