### ISSUE TITLE
[Bug]: crash app

### ISSUE THREAD

**Issue by XueyiXia** [android/nowinandroid#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

just run app ，it is crash 

### Relevant logcat output

```shell
Process: com.google.samples.apps.nowinandroid.demo.debug, PID: 17321
                                                                                                    java.lang.RuntimeException: StrictMode ThreadPolicy violation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1981)
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0(StrictMode.java:1895)
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.$r8$lambda$AF9hglpXLeeg2_1ZxHCfZb2exEY(Unknown Source:0)
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1726)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8703)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                                                                                                    	at java.io.File.exists(File.java:813)
                                                                                                    	at android.content.res.OplusThemeZipFile.isValidThemeFile(OplusThemeZipFile.java:305)
                                                                                                    	at android.content.res.OplusThemeZipFile.getThemeZipFile(OplusThemeZipFile.java:237)
                                                                                                    	at android.content.res.OplusThemeResources.checkUpdate(OplusThemeResources.java:162)
                                                                                                    	at android.content.res.OplusThemeResourcesSystem.checkUpdate(OplusThemeResourcesSystem.java:50)
                                                                                                    	at android.content.res.ResourcesImplExt.checkUpdate(ResourcesImplExt.java:395)
                                                                                                    	at android.content.res.ResourcesImpl.updateConfiguration(ResourcesImpl.java:545)
                                                                                                    	at android.content.res.ResourcesImpl.<init>(ResourcesImpl.java:197)
                                                                                                    	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:713)
                                                                                                    	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:755)
                                                                                                    	at android.app.ResourcesManager.createResourcesForActivity(ResourcesManager.java:1140)
                                                                                                    	at android.app.ResourcesManager.createBaseTokenResources(ResourcesManager.java:951)
                                                                                                    	at android.app.ContextImpl.createActivityContext(ContextImpl.java:3460)
                                                                                                    	at android.app.ActivityThread.createBaseContextForActivity(ActivityThread.java:4121)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3894)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4181)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257) 
                                                                                                    	at android.os.Looper.loop(Looper.java:368) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
Interesting... It seems like your OS is trying to apply custom theming (or at least tries to see if a custom theme matches) and reading a file on disk at the same time. Do you happen to have a OnePlus device, or a custom OS with theming support?
This crash will only appear in debug builds, where we want to catch these issues as soon as possible, but not on release builds.

**Comment by XueyiXia** [comment]
> Interesting... It seems like your OS is trying to apply custom theming (or at least tries to see if a custom theme matches) and reading a file on disk at the same time. Do you happen to have a OnePlus device, or a custom OS with theming support? This crash will only appear in debug builds, where we want to catch these issues as soon as possible, but not on release builds.

hi,I have tried to build the app for this project using Samsung A9(Android 10) star lite and OPPO PHW110(android 14), but it still crashes. I also tried the simulator, and the app also crashes.

**Comment by SimonMarquis** [comment]
Can you share the traces for the other devices? There might be other bugs to fix.

**Comment by XueyiXia** [comment]
> Can you share the traces for the other devices? There might be other bugs to fix.

I don't have any other devices, only these two phones, and the app will crash when running on these two phones

**Comment by prdp89** [comment]
Inside MainActivity.kt --> onResume() add this:

`permitDiskReads{
            super.onResume()
        }`

then permitDiskReads method as follows:

` private fun permitDiskReads(func: () -> Any) : Any {
        if (BuildConfig.DEBUG) {
            val oldThreadPolicy = StrictMode.getThreadPolicy()
            StrictMode.setThreadPolicy(
                StrictMode.ThreadPolicy.Builder(oldThreadPolicy)
                    .permitDiskReads().build())
            val anyValue = func()
            StrictMode.setThreadPolicy(oldThreadPolicy)

            return anyValue
        } else {
            return func()
        }
    }`

It solves the issue in the OnePlus device. I don't have other devices to replicate.

**Comment by SimonMarquis** [comment]
We probably won't do that since it defeats the purpose of catching bad behaviors.

**Comment by Jaehwa-Noh** [comment]
@XueyiXia  It is just an workaround for you, not for this project.

If you want to turn off the policy to run on your device.
Simply remove `penaltyDeath()` from `NiaApplication.kt`.


```
private fun setStrictModePolicy() {
        if (isDebuggable()) {
            StrictMode.setThreadPolicy(
                Builder().detectAll().penaltyLog().build(),
            )
        }
    }
```

**Comment by ALI-M0vS5a** [comment]
The crash also happened on my phone motorola one 5G UW ace android 12 


FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.google.samples.apps.nowinandroid.demo.debug, PID: 29197
                                                                                                    java.lang.RuntimeException: StrictMode ThreadPolicy violation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1891)
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0$StrictMode$AndroidBlockGuardPolicy(StrictMode.java:1805)
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy$$ExternalSyntheticLambda0.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:980)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238)
                                                                                                    	at android.os.Looper.loop(Looper.java:357)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8098)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
                                                                                                    Caused by: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1674)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7971)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:332)
                                                                                                    	at java.io.File.exists(File.java:829)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:749)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:740)
                                                                                                    	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:696)
                                                                                                    	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:921)
                                                                                                    	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:543)
                                                                                                    	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
                                                                                                    	at com.google.firebase.remoteconfig.RemoteConfigComponent.getMetadataClient(RemoteConfigComponent.java:313)
                                                                                                    	at com.google.firebase.remoteconfig.RemoteConfigComponent.get(RemoteConfigComponent.java:169)
                                                                                                    	at com.google.firebase.perf.config.RemoteConfigManager.isFirebaseRemoteConfigAvailable(RemoteConfigManager.java:401)
                                                                                                    	at com.google.firebase.perf.config.RemoteConfigManager.triggerRemoteConfigFetchIfNecessary(RemoteConfigManager.java:337)
                                                                                                    	at com.google.firebase.perf.config.RemoteConfigManager.getRemoteConfigValue(RemoteConfigManager.java:301)
                                                                                                    	at com.google.firebase.perf.config.RemoteConfigManager.getBoolean(RemoteConfigManager.java:213)
                                                                                                    	at com.google.firebase.perf.config.ConfigResolver.getRemoteConfigBoolean(ConfigResolver.java:867)
                                                                                                    	at com.google.firebase.perf.config.ConfigResolver.getIsExperimentTTIDEnabled(ConfigResolver.java:826)
                                                                                                    	at com.google.firebase.perf.metrics.AppStartTrace.onActivityResumed(AppStartTrace.java:355)
                                                                                                    	at android.app.Application.dispatchActivityResumed(Application.java:416)
                                                                                                    	at android.app.Activity.dispatchActivityResumed(Activity.java:1448)
                                                                                                    	at android.app.Activity.onResume(Activity.java:2001)
                                                                                                    	at com.google.samples.apps.nowinandroid.MainActivity.onResume(MainActivity.kt:160)
                                                                                                    	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1478)
                                                                                                    	at android.app.Activity.performResume(Activity.java:8386)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4888)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4931)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238) 
                                                                                                    	at android.os.Looper.loop(Looper.java:357) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8098) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 

> 

>

**Comment by XueyiXia** [comment]
> @XueyiXia It is just an workaround for you, not for this project.
> 
> If you want to avoid the policy crash on your device. Simply remove `penaltyDeath()` from `NiaApplication.kt`.
> 
> ```
> private fun setStrictModePolicy() {
>         if (isDebuggable()) {
>             StrictMode.setThreadPolicy(
>                 Builder().detectAll().penaltyLog().build(),
>             )
>         }
>     }
> ```

thank you ！ i remove setStrictModePolicy function ,i can build app successful!

**Comment by ambushwork** [comment]
I have exactly the same issue on my emulator and Samsung SM-S911B

**Comment by Jaehwa-Noh** [comment]
@ambushwork 
Here is a good place leave your error log.

**Comment by Richard0403** [comment]
it also happened on my XiaoMi12S Pro,  Android 14

**Comment by anhtuannd** [comment]
Same problem in Xiaomi Mi 13 Pro, Android 14

**Comment by Sourabhlpu** [comment]
Removing the setStrictModePolicy function installs the app but app is not responding to any clicks.

**Comment by Jaehwa-Noh** [comment]
That's not related with this issue.
See the StrictMode.
https://developer.android.com/reference/android/os/StrictMode

**Comment by anhtuannd** [comment]
I got opportunity to test this on multiple devices today:
|Device|Reproducible?|
|---|---|
|Pixel 8a|No|
|Pixel 9|No|
|Emulator Pixel 9 - API 35|No|
|Xiaomi 13 Pro|**YES**|

**Comment by SMAXLYB** [comment]
> [@XueyiXia](https://github.com/XueyiXia) It is just an workaround for you, not for this project.
> 
> If you want to avoid the policy crash on your device. Simply remove `penaltyDeath()` from `NiaApplication.kt`.
> 
> ```
> private fun setStrictModePolicy() {
>         if (isDebuggable()) {
>             StrictMode.setThreadPolicy(
>                 Builder().detectAll().penaltyLog().build(),
>             )
>         }
>     }
> ```

it works
