### ISSUE TITLE
[Bug]: Could not resolve JNA native support

### ISSUE THREAD

**Issue by Alexminator99** [android/nowinandroid#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

I'm getting this error when trying to build the project in a MAC M1 (IntelliJ Idea Community):

`Caused by: java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1012)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.sun.jna.platform.mac.SystemB.<clinit>(SystemB.java:40)
	at com.android.utils.ComputerArchUtilsKt.computeIsRosetta(ComputerArchUtils.kt:148)
	at com.android.utils.ComputerArchUtilsKt.access$computeIsRosetta(ComputerArchUtils.kt:1)
	at com.android.utils.Environment$Companion$SYSTEM$1.isRosetta(ComputerArchUtils.kt:65)
	at com.android.utils.ComputerArchUtilsKt.getOsArchitecture(ComputerArchUtils.kt:128)
	at com.android.build.gradle.internal.ManagedDeviceUtilsKt.computeAbiFromArchitecture$default(ManagedDeviceUtils.kt:89)
	at com.android.build.gradle.internal.ManagedDeviceUtilsKt.computeAbiFromArchitecture(ManagedDeviceUtils.kt:79)
	at com.android.build.gradle.internal.tasks.ManagedDeviceSetupTask$CreationAction.<init>(ManagedDeviceSetupTask.kt:215)
	at com.android.build.gradle.internal.TaskManager.createTestDevicesTasks(TaskManager.kt:1773)
	at com.android.build.gradle.internal.TaskManager.createTasks(TaskManager.kt:321)
	at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.kt:692)
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2$1.call(BasePlugin.kt:575)
	at com.android.build.gradle.internal.profile.NoOpAnalyticsConfiguratorService.recordBlock(NoOpAnalyticsConfiguratorService.kt:48)
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:570)
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:567)
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)`

I searched for it and I didn't find anything relevant that I could use. I didn't find any references in the open and closed issues here...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Sorry, we only support building this project in Android Studio, or from the terminal `./gradlew build`.
