### ISSUE TITLE
App crashes on android emulator with Android Tiramisu api level 33

### ISSUE THREAD

**Issue by a-fathian** [android/nowinandroid#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

App crashes upon launching in android emulator with api level 33 (Tiramisu)

### Relevant logcat output

```shell
FATAL EXCEPTION: main
                                                                                                    Process: com.google.samples.apps.nowinandroid.demo.debug, PID: 4441
                                                                                                    java.lang.NoSuchMethodError: No virtual method getOnBackInvokedDispatcher()Landroid/window/OnBackInvokedDispatcher; in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
                                                                                                    	at androidx.activity.ComponentActivity$Api33Impl.getOnBackInvokedDispatcher(ComponentActivity.java:1138)
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:382)
                                                                                                    	at com.google.samples.apps.nowinandroid.MainActivity.onCreate(MainActivity.kt:85)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8257)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8237)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1339)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3660)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3816)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:99)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2299)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7850)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smish-hash** [comment]
I am using this on Android 13 API 33 emulator. Not facing any crash.

**Comment by SimonMarquis** [comment]
It does run perfectly on emulators running API 33 here.
From the stacktrace, it seems like your are running on API >= 33 and therefore your device should have access to `Activity.getOnBackInvokedDispatcher`.
Can you confirm you reproduce the issue from a CI build like the latest one here: https://github.com/android/nowinandroid/suites/14270838981/artifacts/802001204 ?

**Comment by a-fathian** [comment]
> It does run perfectly on emulators running API 33 here. From the stacktrace, it seems like your are running on API >= 33 and therefore your device should have access to `Activity.getOnBackInvokedDispatcher`. Can you confirm you reproduce the issue from a CI build like the latest one here: https://github.com/android/nowinandroid/suites/14270838981/artifacts/802001204 ?

I downloaded the zip file from the CI build link and installed the app-demo-debug.apk on the same emulator, the same crash happened again. Maybe there is something wrong with my emaulator

**Comment by alaa-alsalehi** [comment]
I tried to repreduce the issue but it works just fine

PART OF GTC OPEN SOURCE INTIATIVE
