### ISSUE TITLE
[Bug]: Running MacroBenchmark Throw NullPointerException on interestsScrollTopicsDownUp

### ISSUE THREAD

**Issue by alaa-alsalehi** [android/nowinandroid#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

This PR is part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

After run Genrate Baseline Profile I face exception
it looks like the emulator device stop before the interestsScrollTopicsDownUp happened

### Relevant logcat output

```shell
java.lang.NullPointerException
	at com.google.samples.apps.nowinandroid.interests.InterestsActionsKt.interestsScrollTopicsDownUp(InterestsActions.kt:38)
	at com.google.samples.apps.nowinandroid.baselineprofile.BaselineProfileGenerator$generate$1.invoke(BaselineProfileGenerator.kt:56)
	at com.google.samples.apps.nowinandroid.baselineprofile.BaselineProfileGenerator$generate$1.invoke(BaselineProfileGenerator.kt:38)
	at androidx.benchmark.macro.BaselineProfilesKt$collect$1$1.invoke(BaselineProfiles.kt:77)
	at androidx.benchmark.macro.BaselineProfilesKt$collect$1$1.invoke(BaselineProfiles.kt:71)
	at androidx.benchmark.macro.CompilationMode$Partial.compileImpl$benchmark_macro_release(CompilationMode.kt:319)
	at androidx.benchmark.macro.CompilationMode.resetAndCompile$benchmark_macro_release(CompilationMode.kt:115)
	at androidx.benchmark.macro.BaselineProfilesKt.collect(BaselineProfiles.kt:71)
	at androidx.benchmark.macro.junit4.BaselineProfileRule.collect(BaselineProfileRule.kt:136)
	at androidx.benchmark.macro.junit4.BaselineProfileRule.collect$default(BaselineProfileRule.kt:126)
	at com.google.samples.apps.nowinandroid.baselineprofile.BaselineProfileGenerator.generate(BaselineProfileGenerator.kt:38)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
@alaa-alsalehi can you share the exact Gradle task you used to trigger this? (and any emulator/device info you have)

**Comment by alaa-alsalehi** [comment]
Sure here is the gradle task `:benchmarks:pixel6api31aospDemoBenchmarkAndroidTest`
and this is the full run
`:benchmark:pixel6api31aospDemoBenchmarkAndroidTest --rerun --enable-display -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile`

**Comment by SimonMarquis** [comment]
Thanks, can you check if you still reproduce the issue with this PR?
- #858

**Comment by alaa-alsalehi** [comment]
I clone your fork and yes still have the same issue and here is the stack trace again if there is any different based on your updates
```
java.lang.NullPointerException
	at com.google.samples.apps.nowinandroid.interests.InterestsActionsKt.interestsScrollTopicsDownUp(InterestsActions.kt:38)
	at com.google.samples.apps.nowinandroid.baselineprofile.BaselineProfileGenerator$generate$1.invoke(BaselineProfileGenerator.kt:58)
	at com.google.samples.apps.nowinandroid.baselineprofile.BaselineProfileGenerator$generate$1.invoke(BaselineProfileGenerator.kt:39)
	at androidx.benchmark.macro.BaselineProfilesKt$collect$1$2.invoke(BaselineProfiles.kt:89)
	at androidx.benchmark.macro.BaselineProfilesKt$collect$1$2.invoke(BaselineProfiles.kt:83)
	at androidx.benchmark.macro.CompilationMode$Partial.compileImpl$benchmark_macro_release(CompilationMode.kt:319)
	at androidx.benchmark.macro.BaselineProfilesKt.collect(BaselineProfiles.kt:83)
	at androidx.benchmark.macro.junit4.BaselineProfileRule.collect(BaselineProfileRule.kt:136)
	at androidx.benchmark.macro.junit4.BaselineProfileRule.collect$default(BaselineProfileRule.kt:126)
	at com.google.samples.apps.nowinandroid.baselineprofile.BaselineProfileGenerator.generate(BaselineProfileGenerator.kt:39)
```

**Comment by SimonMarquis** [comment]
I've reproduced the issue on my end.
Adding a small delay before the fling gesture fixed the issue.
Can you check again?

**Comment by alaa-alsalehi** [comment]
@SimonMarquis looks like the issue solved I can not repreduce
